version: "3.8"

services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  memorabel-parser:
    image: pmateus/memorabel-data-harmonization:1.1.1
    stdin_open: true
    tty: true
    environment:
      DB_USER: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: CDM
      DOCKER_ENV: 1
      VOCABULARY_PATH: /usr/src/app/vocabularies
      DESTINATION_MAPPING_PATH: /mnt/mappings/destination_mapping.csv
      SOURCE_MAPPING_PATH: /mnt/mappings/source_mapping.csv
      DATASET_PATH: /mnt/data/dataset.csv
      DATASET_DELIMITER: ","
      SOURCE_NAME: CDM database for Cohort 1
      HOLDER: Cohort 1 Administrator
      DESCRIPTION:
      REFERENCE:
      ETL_REFERENCE: https://gitlab.com/UM-CDS/projects/memorabel/-/tree/master/data_harmonization
      CDM_VERSION: 6.0
      VOCABULARY_VERSION: 1.0
      FOLLOW_UP_SUFFIX: "_FU1;_FU2"
      IGNORE_ENCODING_ERRORS: 0
      ENCODING: "UTF-8"
      MISSING_VALUES: "-999"
    volumes:
      - $PWD/mappings:/mnt/mappings
      - $PWD/data:/mnt/data
    depends_on:
      - db
