version: "3.0"

services:
  # ms_v2:
  #   image: postgres:12.6
  #   container_name: mockdata_db_1
  #   environment:
  #     POSTGRES_USER: username
  #     POSTGRES_PASSWORD: ""

  memorabel-parser:
    image: pmateus/memorabel-data-harmonization:1.7.6
    stdin_open: true
    tty: true
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: vantage6-rdb
      DB_PORT: 5432
      DB_DATABASE: UmDB
      DOCKER_ENV: 1
      VOCABULARY_PATH: /usr/src/app/vocabularies
      DESTINATION_MAPPING_PATH: /mnt/mappings/destination_mapping.csv
      SOURCE_MAPPING_PATH: /mnt/mappings/source_mapping.csv
      DATASET_PATH: /mnt/data/dataset.sav
      DATASET_DELIMITER:
      SOURCE_NAME: Maastricht PHT
      HOLDER:
      DESCRIPTION: Data from the Maastricht Study for the PHT
      REFERENCE:
      ETL_REFERENCE: https://gitlab.com/UM-CDS/projects/memorabel/-/tree/master/data_harmonization
      CDM_VERSION: 6.0
      VOCABULARY_VERSION: 1.0
      FOLLOW_UP_SUFFIX:
      ENCODING: "iso-8859-1"
      MISSING_VALUES:
      IGNORE_DUPLICATES: 1 
    volumes:
      - ./source_mapping.csv:/mnt/mappings/source_mapping.csv
      - ./destination_mapping.csv:/mnt/mappings/destination_mapping.csv
      - /dataset.sav:/mnt/data/dataset.sav
      - ./backup:/mnt/backup
